### ISSUE TITLE
Add option to include all but some files

### ISSUE THREAD

**Issue by kevya-google** [abcxyz/abc#131]
### TL;DR

Currently the only way to do this is by specifying every file to be included. An "include all but X" would be convenient to have.

cc @verbanicm @drevell

**Comment by drevell** [comment]
I had forgotten this until I just saw it in the source code, but I already implemented one version of this: https://github.com/abcxyz/abc/blob/cd9db9a341951066442084bbdc788fd7dca24553/templates/model/spec.go#L313 . We may want to redesign it with our latest thoughts though. cc @kevya-google

**Comment by kevya-google** [comment]
Will rename to exclude.

**Comment by kevya-google** [comment]
Discussed offline, we're ok with keeping this as skip.
