### ISSUE TITLE
regex_replace and regex_name_lokup actions don't apply templates on paths input

### ISSUE THREAD

**Issue by pdewilde** [abcxyz/abc#142]
### TL;DR

The readme says:

```
paths: A list of files and/or directories in which to do the replacement. May use template expressions (e.g. {{.my_input}}).
```

but template expressions on the paths input are never evaluated in the code for both the `regex_replace` and `regex_name_lookup` actions. For an example of how to fix look at [templates/commands/render_action_stringreplace.go](https://github.com/abcxyz/abc/blob/90e065b0f06b362f559010ae0bffa166de3c1303/templates/commands/render_action_stringreplace.go#L40) where `parseAndExecuteGoTmpl` is applied to the paths.

### Environment Details

```markdown
N/A
```

**Comment by drevell** [comment]
Starting work on this now.
