### ISSUE TITLE
Supply hash for --version flag when from source, rather than HEAD

### ISSUE THREAD

**Issue by pdewilde** [abcxyz/abc#148]
### TL;DR

Currently when you install with `go install` you get:
```
$ abc --version
abc source (HEAD, linux/amd64)
```

It would be helpful to get the git hash of the commit, as HEAD tells you nothing about the version of the CLI you are running. An additional improvement would be to also show the date of the commit.

**Comment by pdewilde** [comment]
Currently commits/versions come from goreleaser https://github.com/abcxyz/abc/blob/main/.goreleaser.yaml#L37

**Comment by pdewilde** [comment]
It should be coming from https://github.com/abcxyz/abc/blob/07104eadd948b2e70bed256ade2b5949d4415051/internal/version/version.go#L32-L41 but something seems to be failing so its falling back to HEAD for some reason.

**Comment by sethvargo** [comment]
It comes from that func, unless the LDFLAG is set by goreleaser. Perhaps that function isn't working as intended? Are you building with `go build` or using an IDE?

**Comment by pdewilde** [comment]
I am using  `go install github.com/abcxyz/abc/cmd/abc@latest` in my terminal

**Comment by sethvargo** [comment]
@pdewilde I think that makes sense. The VCS information is only injected when you're building from a local repo. Can you try with `go build` from a clone of this repo?

**Comment by drevell** [comment]
I just sent #149 which I think resolves this by printing the module version from the buildinfo.
