### ISSUE TITLE
Fail with a helpful error if the user puts flags in the wrong spot

### ISSUE THREAD

**Issue by drevell** [abcxyz/abc#380]
### TL;DR

If the user does `abc templates render mytemplate --input=foo-bar`, then it will fail confusingly because the flags should go before the template name. We could probably detect this and print a helpful error message.

Ideas:
 - Look at the positional arguments to each command. If there are more positional args than there should be, and if some of them start with "-", then there has probably been a mistake and we can fail or print a warning.

**Comment by sethvargo** [comment]
Why wouldn't we expect it to work? I always personally get annoyed when flags need to be before/after a certain positional argument.

**Comment by drevell** [comment]
Re @sethvargo I think this is a limitation of github.com/abcxyz/pkg/cli library. Do you think we should fix it there?

**Comment by sethvargo** [comment]
Oh? Can you open an issue or PR with some failing tests? That's definitely *not* WAI.

**Comment by drevell** [comment]
@sethvargo I think this is the intended behavior of the stdlib flag parser which underlies the pkg/cli flag parser. The docs (https://pkg.go.dev/flag#hdr-Command_line_flag_syntax) say `Flag parsing stops just before the first non-flag argument ("-" is a non-flag argument) or after the terminator "--".`

Here's a repro branch in the pkg repo: https://github.com/abcxyz/pkg/compare/main...drevell/flags-positional-repro

**Comment by sethvargo** [comment]
https://github.com/abcxyz/pkg/pull/263

**Comment by drevell** [comment]
Fixed by https://github.com/abcxyz/pkg/pull/263 (thanks Seth)

**Comment by sethvargo** [comment]
Thanks - I'm gonna release that as v0.7.1; we'll need to update the deps to pull it in.
