### ISSUE TITLE
On Windows, line endings break golden-tests

### ISSUE THREAD

**Issue by drevell** [abcxyz/abc#400]
Sometimes, the recorded golden test output directories are corrupted by being checked out on Windows. Here's what I think is happening:

1. On a non-windows machine, somebody runs `abc templates golden-test record`. The test output is duly recorded in the testdata directory. The user runs `git commit` and submits a PR. Everything is working correctly.
2. On a windows machine, `git checkout` is run. This could be a CI test on windows, or a user workstation. On windows, the `autocrlf` option defaults to true, which means line endings on text files are converted from LF (0x0a) to CRLF (0x0d0a). This essentially corrupts the `testdata` directory if it contains any text files.
3. The `abc templates golden-test verify` command is run, either by a user or by CI. This reports a test failure because the actual template output differs from the autocrlf-corrupted golden output.

Workaround:
 - Disable the `autocrlf` option in Github Actions using `- run: 'git config --global core.autocrlf false'`. This works around the problem for CI, but doesn't fix the problem for user workstations.

Possible fix:
 - Make the `golden-test record` command output a `.gitattributes` that instructs git to disable the `autocrlf` option for the recorded test output directory.
 - Remove Windows support, it's costing us time and effort and providing no value.

**Comment by capri-xiyue** [comment]
No need to fix it as we removed windows support in #405
