### ISSUE TITLE
Tab completion doesn't work for positional args

### ISSUE THREAD

**Issue by drevell** [abcxyz/abc#453]
As a CLI user, I want to be able to tab-complete local template paths and local goldentest paths.

What works:
 - If I type `abc templates golden-test ver` and hit tab, it correctly completes `ver` as `verify`.
 - If I type `abc templatess golden-test verify -` and hit tab, it correctly offers me all the flag names.

What doesn't work yet, that I want to work:
 - If I type `abc templates golden-test verify ./my-local-d` and hit tab, it doesn't autocomplete to `my-local-dir`, but it should.

So we need to figure out how to integrate with our CLI library to provide this information.

Background on setting up tab-completions: https://github.com/abcxyz/abc//?tab=readme-ov-file#tab-autocompletion

**Comment by sethvargo** [comment]
https://github.com/abcxyz/pkg/blob/4b8d5d3674c9fd86b1796142ca6a6b6b834b49b1/cli/command_doc_completions_test.go#L48-L52

**Comment by drevell** [comment]
Thanks @sethvargo !
