### ISSUE TITLE
Change "abc templates" from being a subcommand to the only command

### ISSUE THREAD

**Issue by drevell** [abcxyz/abc#507]
Per an approved [internal doc](https://docs.google.com/document/d/1_LdODY1jbG2Cn_8aNTtGiKCMh6-GsMZqF1ce1muqiUk/edit?usp=sharing&resourcekey=0-QXZJMDNwPK7ZXa6_Fiy2fQ), we're abandoning the idea that `abc` will be a swiss-army knife of CLI tools. It has now been declared a single purpose tool for templating (including `render`, `golden-test`, `upgrade`, etc).

So basically we want to re-home everything from under `abc templates` to just being under `abc`. We should also keep the old (`abc templates foo`) subcommands so we don't break the commands that everyone is accustomed to using. And change the docs and scripts to prefer the newer, shorter form of commands.

**Comment by sethvargo** [comment]
You should be able to mount the same subcommand at root and at "templates", hiding "templates". That will give you backwards compat.

**Comment by drevell** [comment]
@sethvargo nice, thanks, will do.
