### ISSUE TITLE
"impossible condition" warning in TestProcessGlobs

### ISSUE THREAD

**Issue by drevell** [abcxyz/abc#508]
This line of code is giving a compiler warning of `impossible condition: nil != nil`: https://github.com/abcxyz/abc/blob/23bee49450c6b00195da7b3c3dc94fbab60703b8/templates/common/render/action_test.go#L543

@kevya-google , as the author of this, do you know what was intended here? It's not immediately clear to me.

**Comment by sethvargo** [comment]
Looks like this might have been a bad merge conflict resolution (the same stanza is repeated 3 lines up)
