### ISSUE TITLE
TestDiff/files_differ_with_color_on_machine_with_color_support fails in local

### ISSUE THREAD

**Issue by capri-xiyue** [abcxyz/abc#534]
### TL;DR

https://github.com/abcxyz/abc/blob/49babab96513de693386e38b4ca1ff6a335aeeb1/templates/common/run/diff_test.go#L107 This test case will fail when I run `go test` in local. But it will pass in CI/CD

### Environment Details

```markdown
mac
```

**Comment by drevell** [comment]
@capri-xiyue Thanks for filing this. Could you provide more information?

 - What kind machine is this running on (Mac, Linux)
 - Please provide the full command line command that you ran, and the test output.
 - Please provide the output of `go version`
 - Anything else that can help reproduce the problem

Thanks!

**Comment by capri-xiyue** [comment]
> @capri-xiyue Thanks for filing this. Could you provide more information?
> 
> * Please provide the full command line command that you ran, and the test output.
> * Please provide the output of `go version`
> * Anything else that can help reproduce the problem
> 
> Thanks!


1. I ran `go test ./...` and the output is attached
<img width="720" alt="Screenshot 2024-04-12 at 12 12 08 PM" src="https://github.com/abcxyz/abc/assets/52932582/2b711a97-2e5b-4c6d-8ea6-0ea0c3dc0ce2">
2. `go version go1.22.1 darwin/amd64`
3. I run it in mac os sonoma 14.4.1
