### ISSUE TITLE
Implement `templates describe <url>`

### ISSUE THREAD

**Issue by drevell** [abcxyz/abc#62]
### TL;DR

We want users to be able to find out information about a template, like:

 - The description
 - The set of inputs: which are required, what are their descriptions, what are their names

One possible design: we add a new subcommand `templates describe` that downloads a template, parses it's spec file, and prints out the metadata about the template in a human-friendly format.

Another idea: formalize the convention that "README.md must exist and contain usage instructions for the template, expected to be a few hundred words long at least" 

CC @verbanicm who mentioned this.

**Comment by drevell** [comment]
Edited description to add this comment: "Another idea: formalize the convention that "README.md must exist and contain usage instructions for the template, expected to be a few hundred words long at least""

**Comment by drevell** [comment]
Now that we support git tags as template versions, the `describe` command should also print a list of versions (or maybe just the latest version). This can use the `Tags()` function in git.go along with some parsing code like https://github.com/abcxyz/abc/blob/9314a9adf480cf8014d70ced3f4b4caa56de3133/templates/commands/render/templatesource/git.go#L180-L197 .

**Comment by drevell** [comment]
I think we should consider adding docs for this before calling it complete

**Comment by sailorlqh** [comment]
> I think we should consider adding docs for this before calling it complete

Oh yeah, I will update docs.
